// AUTO GENERATED BY config-gen DO NOT MODIFY BY HAND

#ifndef IMSHARK_PACKET_CONFIGS_H
#define IMSHARK_PACKET_CONFIGS_H

#include <string>
#include <vector>

namespace imshark::core::configs
{
    struct config_field
    {
        std::string name;
        int size;
    };

    struct config
    {
        std::string name;
        std::string depends_on;
        int size;
        std::vector<config_field> fields;

        bool operator==(const config& config) const
        {
            if (fields.size() != config.fields.size())
            {
                return false;
            }

            for (int i = 0; i < fields.size(); ++i)
            {
                if (fields[i].name != config.fields[i].name || fields[i].size != config.fields[i].size)
                {
                    return false;
                }
            }

            return name == config.name && depends_on == config.depends_on && size == config.size;
        }
    };

    static std::vector<config> PACKET_CONFIGS = {
        REPLACE_CONFIGS
    };

    static std::vector<config> ROOT_PACKET_CONFIGS = {
        REPLACE_ROOT_CONFIGS
    };
}

#endif