// AUTO GENERATED BY config-gen DO NOT MODIFY BY HAND

#ifndef IMSHARK_PACKET_CONFIGS_H
#define IMSHARK_PACKET_CONFIGS_H

#include <string>
#include <vector>

namespace imshark::core::configs
{
    struct config_field
    {
        std::string name;
        int size;
    };

    struct config
    {
        std::string name;
        std::string depends_on;
        int size;
        std::vector<config_field> fields;
    };

    static std::vector<config> PACKET_CONFIGS = {
        REPLACE_CONFIGS
    };
}

#endif