// AUTO GENERATED BY config-gen DO NOT MODIFY BY HAND

#ifndef IMSHARK_PACKET_CONFIGS_H
#define IMSHARK_PACKET_CONFIGS_H

#include <string>
#include <vector>

namespace imshark::core::configs
{
    struct config_field
    {
        std::string name;
        int size;
    };

    struct config
    {
        std::string name;
        std::string depends_on;
        int size;
        std::vector<config_field> fields;
    };

    static std::vector<config> PACKET_CONFIGS = {
        config{"eth","",112,std::vector<config_field>{config_field{"destination",48},config_field{"source",48},config_field{"type",16}}},config{"ip","eth",160,std::vector<config_field>{config_field{"version",4},config_field{"header length",4},config_field{"differentiated services codepoint",6},config_field{"explicit congestion notification",2},config_field{"total length",16},config_field{"identification",16},config_field{"flags",3},config_field{"dont fragment",13},config_field{"time to live",8},config_field{"protocol",8},config_field{"header checksum",16},config_field{"source address",32},config_field{"destination address",32}}}
    };
}

#endif